substitutions:
  name: 4-countdown
  friendly_name: 4-countdown
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: tu5mp4BZuW5EqX5JXkd+Ln3naFT1CStzMuE6VtVhekE=
  reboot_timeout: 0s # Prevent reboots when unmanaged

wifi: !secret wifi  # Makes demo smoother

# START ****************************
binary_sensor:
  # Remove the power_button config provided by AtHom
  - id: !remove power_button
  - platform: gpio
    id: my_button
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: True
    name: "Auto Off"
    on_press:
      - switch.turn_on: relay
      - delay: 5s
      - switch.turn_off: relay
# END ****************************
